apiVersion: v1
kind: Pod
metadata:
  name: dash-debug
spec:
  containers:
  - env:
    - name: DASH_RPC_USER
      valueFrom:
        secretKeyRef:
          name: dash-secret
          key: rpcuser
    - name: DASH_RPC_PASSWORD
      valueFrom:
        secretKeyRef:
          name: dash-secret
          key: rpcpass
    image: ubuntu
    args: ["sleep", "1000000"]
    name: dash-debug
    volumeMounts:
      - mountPath: /data
        name: dash-data
  restartPolicy: Always
  volumes:
    - name: dash-data
      gcePersistentDisk:
        pdName: dash-data
        fsType: ext4
