apiVersion: v1
kind: Pod
metadata:
  name: dash-debug
spec:
  containers:
  - env:
    - name: RPCUSER
      valueFrom:
        secretKeyRef:
          name: dash-secret
          key: rpcuser
    - name: RPCPASSWORD
      valueFrom:
        secretKeyRef:
          name: dash-secret
          key: rpcpass
    image: ubuntu
    args: ["sleep", "1000000"]
    name: dash-debug
    volumeMounts:
      - mountPath: /data
        name: dashd-data
  restartPolicy: Always
  volumes:
    - name: dashd-data
      gcePersistentDisk:
        pdName: dashd-data
        fsType: ext4
