apiVersion: batch/v1
kind: Job
metadata:
  name: dash-backup-job
spec:
  template:
    metadata:
      name: dash-backup-job
    spec:
      containers:
      - name: cloud-sdk
        image: google/cloud-sdk
        command: ["gcloud"]
        args: ["compute", "disks", "snapshot", "dashd-data", "--zone", "us-central1-c"]
      restartPolicy: OnFailure
