apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dash
spec:
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: dash
    spec:
      containers:
      - name: dash
        image: dashpay/dashd:latest
        env:
        - name: DASH_RPC_USER
          valueFrom:
            secretKeyRef:
              name: dash-secret
              key: rpcuser
        - name: DASH_RPC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dash-secret
              key: rpcpass
        volumeMounts:
          - mountPath: /data
            name: dash-data
        resources:
          requests:
            memory: "2Gi"
      restartPolicy: Always
      volumes:
        - name: dash-data
          gcePersistentDisk:
            pdName: dash-data
            fsType: ext4
