apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dash
spec:
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: dash
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: dash
        image: petarbukvic/dashd:latest
        env:
        - name: TESTNET
          value: "1"
        - name: RPCUSER
          valueFrom:
            secretKeyRef:
              name: dash-secret
              key: rpcuser
        - name: RPCPASSWORD
          valueFrom:
            secretKeyRef:
              name: dash-secret
              key: rpcpass
        volumeMounts:
          - mountPath: /dash
            name: dashd-data
        resources:
          requests:
            memory: "2Gi"
      restartPolicy: Always
      volumes:
        - name: dashd-data
          gcePersistentDisk:
            pdName: dashd-data
            fsType: ext4
